### ISSUE TITLE
Allow single eval_target estimate evaluation

### ISSUE THREAD

**Issue by Chadys** [sigsep/sigsep-mus-eval#52]
Currently, when trying to evaluate a single estimate type like 'vocals', the evaluation is silently not doing anything. If the evaluation of one `eval_target` is technically possible, it should be done. If it isn't the documentation should be updated to warn that at least two `eval_targets` are needed and a warning should be logged when using `eval_mus_dir`or `eval_mus_track` incorrectly.

**Comment by faroit** [comment]
thanks for your comment. 

bsseval is a metrics that requires an interference source by definition. While it is possible to compute the residual signal of the target and the mixture, this should not be done inside of bsseval since this could heavily influence the metric (e.g. when just doing `mix - target` in the time domain). If you are only interested in audio quality of the estimated source, ignoring interferences, you could use metrics such as PEAQ or even just use a simple MSE.

You are indeed right that `museval` should be more verbose on this. Would you be willing to make a pull request or proposal how a helpful warning could look like?

**Comment by Chadys** [comment]
Thanks for your feedback.
Correct me if I'm wrong but that means that it would also be incorrect to launch the evaluation only on, let's say, `drums` and `bass` ? You would also need `other` and `vocals` to have access to all of the possible interferences no ?
And yes I'm willing to make a pull request, I'll look into it in the next week or so.

**Comment by faroit** [comment]
can this be closed?

**Comment by Chadys** [comment]
Well the doc hasn't been updated yet, and I was waiting for an answer to my previous question to make a pull request. Depending on the wanted behaviour, I will adapt how I change the docs and what eventual warnings I add.

**Comment by faroit** [comment]
> Correct me if I'm wrong but that means that it would also be incorrect to launch the evaluation only on, let's say, drums and bass ? You would also need other and vocals to have access to all of the possible interferences no ?

All computations are per source, so if you provide estimates and targets for `drums` and `bass`, bsseval assumes a linear mix of these and `bass` would be the inference source for a `drums` target and vice versa. 

I would propose to raise a warning if only one estimate is provided.
