### ISSUE TITLE
Evaluation with single channel source separation

### ISSUE THREAD

**Issue by Yossarian0916** [sigsep/sigsep-mus-eval#69]
How many channels does `track.audio` have, stereo or single channel? Is there a parameter to control the track.audio is output as a single channel audio track, like using `librosa.load()` where I can set `mono=True`?

**Comment by faroit** [comment]
@Yossarian0916 musdb18 tracks are all stereo. You would have to downmix yourself.

**Comment by Yossarian0916** [comment]
Does this mean that the `eval_mus_track()` will evaluate my single channel `estimates` with stereo `track.audio` as the reference track?

**Comment by faroit** [comment]
unfortunately this is not possible at the moment. For now you would have to manually call `museval.evaluate()` instead of `eval_mus_track()`. To allow single channel evaluation on MUSDB18 tracks changed would have to be made to [musdb](https://github.com/sigsep/sigsep-mus-db). Feel free to open an issue there as well or help and make a PR.

**Comment by aliutkus** [comment]
I think it's very easy to apply your single channel method on each channel, to obtain a stereo estimate.
then, you could decide to use `norbert` to enhance this, if you like

**Comment by faroit** [comment]
@Yossarian0916 can this be closed?
