### ISSUE TITLE
Evaluation results vary with volume

### ISSUE THREAD

**Issue by nx5216** [sigsep/sigsep-mus-eval#73]
when I change the volume of estimates, the results by museval will be different, but when I use mir_eval, the results will not change. Is there any difference between museval and mir_eval?

**Comment by faroit** [comment]
there are differences between museval and mir_eval. If you want the same results in museval as in mir_eval, you have to use `mode='v3'` instead of the default. 

Please tell me if that helps.

**Comment by nx5216** [comment]
I have tried museval with mode='v3',but the results still change by volume,here is the results:
museval:
![image](https://user-images.githubusercontent.com/49195787/82543692-8b1bcf80-9b86-11ea-85ab-fa834551f94c.png)
mir_eval:
![image](https://user-images.githubusercontent.com/49195787/82543811-b30b3300-9b86-11ea-8a9c-e471a65007aa.png)
if i want to use museval,is it necessary to adjust the volume to a proper value? I think The method of evaluation should be independent of volume.

**Comment by faroit** [comment]
@aliutkus any idea?

**Comment by fxmarty** [comment]
Isn't it because in [this](https://github.com/sigsep/sigsep-mus-eval/blob/8eff40225c8a11b9bd4b764f235460212b729036/museval/__init__.py#L404) call `bsseval_sources_version` is always set to `False` even when we set `mode='v3'`? This means, according to explanations in `metrics.py` that `bss_eval_image` will be used for the computation, which is dependent to scale but do not introduce fancy filters.

Correct me if I am wrong, but the only thing `mode` is changing is that, for `bss_eval_source`, the allowed distortion filter is the same over the whole track and not varying over time. For `bss_eval_image`, I am not sure what the version is changing.

If one wants to have a constant SDR no matter the scaling, there are two choices:

1. Use `bss_eval_source` e.g. from `mir_eval`. The latent cost is that it allows some distortions that may be unwanted, e.g. for MUSDB it makes no sense to allow distortions that are supposed to reflect the difference between the sources and microphones, when you actually just sum up the individual sources to produce the mixture (as in open-unmix).
2. Use SI-SDR as defined in the original 2006 paper on metrics, same as proposed in [this](https://arxiv.org/abs/1811.02508?) paper.

Something I don't really understand in the end is what "SDR" means in SiSeC 2018 and in subsequent papers. From what I understand, it means that the "raw" SDR `bss_eval_image` has been used. But what about the scaling? How do we know that some results weren't made artificially better just by scaling?

Hopefully from my understanding of the previous paper introducing SI-SDR, it happens that the "raw" SDR is upper-bounded for one given target and estimate. But does it mean that papers using `bss_eval_image` rescaled its output to maximize SDR?

**Comment by fxmarty** [comment]
Sorry to tag, but in case you did not see it @faroit @aliutkus

**Comment by faroit** [comment]
@fxmarty sorry for the late reply. As I remember, we have made the decision to make `bss_eval_images` the default for music tasks and we wanted to prevent people from continue using `bss_eval_sources`.

> Something I don't really understand in the end is what "SDR" means in SiSeC 2018 and in subsequent papers. From what I understand, it means that the "raw" SDR bss_eval_image has been used. But what about the scaling? How do we know that some results weren't made artificially better just by scaling?

i guess you don't. the normal SDR is not scale invariant, and its likely that results are worse for some methods due to some bad scaling (e.g. badly reconstructive STFT).

I guess, @aliutkus has some opinions but you better contact him via mail ;-)
