### ISSUE TITLE
Option to parallelize evaluation

### ISSUE THREAD

**Issue by lminer** [sigsep/sigsep-mus-eval#75]
Is there an option to use multiprocess the evaluation? In the readme.md, it says multiprocessing can be enabled by setting `parallel=True`, but there doesn't appear to be this option in the [signature ](https://github.com/sigsep/sigsep-mus-eval/blob/master/museval/__init__.py#L138) of the function. Was this taken out? Could be a nice extra.

**Comment by faroit** [comment]
ah, yes, I took that out of museval since most users found it tricky to handle numpy parallelism for the actual computation + multiprocessing, often lead to decrease in performance.

You will find the parallel version e.g. in [open-unmix](https://github.com/sigsep/open-unmix-pytorch/blob/master/eval.py#L120)

> In the readme.md, it says multiprocessing can be enabled by setting parallel=True

removed that. Tanks for the hint.
